services:
  postgresql: # 컨테이너 이름
    image: postgres # 이미지 이름
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # 볼륨 설정
    #volumes:
    #  - ./data/postgres/:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
    #volumes:
    #  - ./data/pgadmin/:/var/lib/pgadmin